#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J fastqc
#SBATCH -t 00:59:00

module load bioinfo-tools
module load FastQC

HOME=/home/alexab/plankton2022
PATHIN=$HOME/data/rawdata/3_Thrash_2017/DNA_trimmed
ARCHIVE=
DIROUT=DNA_trimmed/$ARCHIVE

if ! [ -d $HOME/results/FastQC ]
then
mkdir $HOME/results/FastQC
fi

mkdir $HOME/results/FastQC/$DIROUT
cd $PATHIN
fastqc SRR4342129_1.paired.trimmed.fastq.gz  SRR4342129_2.paired.trimmed.fastq.gz  SRR4342133_1.paired.trimmed.fastq.gz  SRR4342133_2.paired.trimmed.fastq.gz  --outdir=$HOME/results/FastQC/$DIROUT
 
