#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J metaqst
#SBATCH -t 04:00:00

module load bioinfo-tools
module load quast

HOME=/home/alexab/plankton2022
PATHIN=$HOME/results/assembly
ARCHIVES=(SRR4342129 SRR4342133)

REFDATA=$HOME/data/metaquast/test_data

DIROUT=$HOME/results/metaquast

if ! [ -d $DIROUT ]
then
mkdir $DIROUT
fi

for a in ${ARCHIVES[@]}
do
mkdir $DIROUT/$a
metaquast.py $PATHIN/$a/final.contigs.fa -r $REFDATA/meta_ref_1.fasta,$REFDATA/meta_ref_2.fasta,$REFDATA/meta_ref_3.fasta -t 2 -o $DIROUT/$a
done

 
