#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J bwadna
#SBATCH -t 24:00:00

module load bioinfo-tools
module load bwa
module load samtools
module load MetaBat

HOME=/home/alexab/plankton2022
ARCHIVES=(SRR4342133)
READSPATH=/home/alexab/plankton2022/data/rawdata/3_Thrash_2017/DNA_trimmed

if ! [ -d $HOME/results/DNA_mapping ]
then
mkdir $HOME/results/DNA_mapping
fi

if ! [ -d $HOME/results/metabat ]
then
mkdir $HOME/results/metabat
fi

for A in ${ARCHIVES[@]}
do
REF=$HOME/results/assembly/$A/final.contigs.fa

mkdir $HOME/results/DNA_mapping/$A
MIDPATH=$HOME/results/DNA_mapping/$A

mkdir $HOME/results/metabat/$A
OUTPATH=$HOME/results/metabat/$A

PAIRF=$READSPATH/${A}_1.paired.trimmed.fastq.gz
PAIRR=$READSPATH/${A}_2.paired.trimmed.fastq.gz

bwa index $REF
bwa mem -t 2 $REF $PAIRF $PAIRR | samtools sort -@ 2 -o $MIDPATH/$A.bam

jgi_summarize_bam_contig_depths --outputDepth $OUTPATH/depth.txt --pairedContigs $OUTPATH/paired.txt $MIDPATH/*.bam

metabat -i $REF -a $OUTPATH/depth.txt -p $OUTPATH/paired.txt -o $OUTPATH/bin3 --specific -l -v --saveTNF $OUTPATH/saved.tnf --saveDistance $OUTPATH/saved.gprob

done


