#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 6
#SBATCH -J phyloP
#SBATCH -t 06:00:00

module load bioinfo-tools phylophlan/0.99 python/2.7.15 biopython/1.73 FastTree muscle/3.8.31 usearch/5.2.32

HOME=/home/alexab/plankton2022/
FAADIR=$HOME/results/prokka2/
OUTDIR=/proj/genomeanalysis2022/nobackup/work/alexab/phylophlanORG
ARCHIVES=(SRR4342129 SRR4342133)

input=$SNIC_TMP/input
mkdir $input
project=$input/plankton
mkdir $project

cd $SNIC_TMP
cp -r /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/* .
cp $HOME/data/refgenomes/refaa/* $project
gunzip $project/*

for A in ${ARCHIVES[@]}; do
cd $FAADIR/$A
binlist=$(ls)
for bin in ${binlist[@]}; do
cd $FAADIR/$A
cd $bin
binname=${bin%%.*}
cp ${binname}.faa $project
mv $project/${binname}.faa $project/${A}_${binname}.faa
done
done

echo ">>ls project<<"
ls $project

cd $SNIC_TMP
chmod 777 phylophlan.py
phylophlan.py -u plankton --nproc 6

mkdir $OUTDIR

cp -r $SNIC_TMP/output/plankton/* $OUTDIR
