#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J metabat
#SBATCH -t 24:00:00

module load bioinfo-tools
module load MetaBat

HOME=/home/alexab/plankton2022
ARCHIVES=(SRR4342133)

if ! [ -d $HOME/results/DNA_mapping ]
then
mkdir $HOME/results/DNA_mapping
fi

if ! [ -d $HOME/results/metabat ]
then
mkdir $HOME/results/metabat
fi

for A in ${ARCHIVES[@]}
do

REF=$HOME/results/assembly/$A/final.contigs.fa
MIDPATH=$HOME/results/DNA_mapping/$A

#mkdir $HOME/results/metabat/$A
OUTPATH=$HOME/results/metabat/$A

#jgi_summarize_bam_contig_depths --outputDepth $OUTPATH/depth.txt --pairedContigs $OUTPATH/paired.txt $MIDPATH/*.bam

metabat -i $REF -a $OUTPATH/depth.txt -p $OUTPATH/paired.txt -o $OUTPATH/bin3 --specific -l -v --saveTNF $OUTPATH/saved.tnf --saveDistance $OUTPATH/saved.gprob

done

