#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J fastqc
#SBATCH -t 00:15:00

# Will run FastQC
# 1st argument = directory containing FastQ files (e.g. data/rawdata/3_Thrash_2017/RNA_untrimmed)
# 2nd argument = output folder (in the FastQC results directory)

module load bioinfo-tools
module load FastQC

HOME=/home/alexab/plankton2022
DIRIN=$HOME/data/rawdata/3_Thrash_2017/RNA_untrimmed
DIROUT=RNA_trimmed
ARCHIVE=SRR4342137


if ! [ -d $HOME/results/FastQC ]
then
mkdir $HOME/results/FastQC
fi

mkdir $HOME/results/FastQC/$DIROUT
cd $DIRIN
fastqc $ARCHIVE.trimmed_fwd_paired.fq.gz $ARCHIVE.trimmed_fwd_unpaired.fq.gz $ARCHIVE.trimmed_rev_paired.fq.gz $ARCHIVE.trimmed_rev_unpaired.fq.gz --outdir=$HOME/results/FastQC/$DIROUT
 
