#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J findadapters
#SBATCH -t 00:05:00

# Will find adapters in fastq sequences

FWDFILE=SRR4342137.1.fastq.gz
REVFILE=SRR4342137.2.fastq.gz
SRCDIR=/home/alexab/plankton2022/data/rawdata/3_Thrash_2017/RNA_untrimmed
OUTFILE=/home/alexab/plankton2022/results/adapters/adapters_137.fa

module load bioinfo-tools
module load bbmap


cd $SRCDIR
bbmerge.sh in1=$FWDFILE in2=$REVFILE outa=$OUTFILE
