#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J megahit2
#SBATCH -t 12:00:00

module load bioinfo-tools
module load megahit

HOME=/home/alexab/plankton2022
PATHIN=$HOME/data/rawdata/3_Thrash_2017/DNA_trimmed
ARCHIVE=SRR4342133
FORWARD=$PATHIN/${ARCHIVE}_1.paired.trimmed.fastq.gz
REVERSE=$PATHIN/${ARCHIVE}_2.paired.trimmed.fastq.gz
DIROUT=$HOME/results/assembly/$ARCHIVE

if ! [ -d $HOME/results/assembly ]
then
mkdir $HOME/results/assembly
fi

cd $PATHIN
megahit -1 $FORWARD -2 $REVERSE -o $DIROUT --kmin-1pass


