#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J trimmomatic.job
#SBATCH -t 00:10:00

module load bioinfo-tools
module load trimmomatic

# Modify this
DIRHOME=/home/alexab/plankton2022
DIRDATA=$DIRHOME/data/rawdata/3_Thrash_2017/RNA_untrimmed
DIRRESULTS=$DIRHOME/results/trimmomatic
ARCHIVE=SRR4342139
ADAPTERS=$DIRHOME/results/adapters/adapters_both.fa

# Check this
INPUTF=$DIRDATA/$ARCHIVE.1.fastq.gz
INPUTR=$DIRDATA/$ARCHIVE.2.fastq.gz

# Don't touch this
# Output files
FLOG=$DIRRESULTS/trim_$ARCHIVE.log
FWDPAIRED=$DIRRESULTS/$ARCHIVE.trimmed_fwd_paired.fq.gz
FWDUNPAIRED=$DIRRESULTS/$ARCHIVE.trimmed_fwd_unpaired.fq.gz
REVPAIRED=$DIRRESULTS/$ARCHIVE.trimmed_rev_paired.fq.gz
REVUNPAIRED=$DIRRESULTS/$ARCHIVE.trimmed_rev_unpaired.fq.gz

if ! [ -e $FLOG ]
then
touch $FLOG
fi


trimmomatic PE -threads 2 -phred33 -trimlog $FLOG $INPUTF  $INPUTR  $FWDPAIRED $FWDUNPAIRED $REVPAIRED $REVUNPAIRED  ILLUMINACLIP:$ADAPTERS:2:30:15 SLIDINGWINDOW:5:30 TRAILING:20 MINLEN:20



